- name: Install & Config Squeezelite
  hosts: mypis
  become: true
  tasks:
  - name: Install Squeezelite
    ansible.builtin.apt:
      name: squeezelite

  - name: Enable HiFiBerry Amp
    ansible.builtin.lineinfile:
      path: /boot/config.txt
      line: dtoverlay=hifiberry-amp
    register: config

  - name: Reboot the box if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible after adding HiFi Berry Amp"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: config.changed

  - name: Change Squeezelite name
    ansible.builtin.lineinfile:
      path: /etc/default/squeezelite
      regexp: '^SL_NAME='
      line: SL_NAME="Kitchen_Squeeze"

  - name: Change Squeezelite output device
    ansible.builtin.lineinfile:
      path: /etc/default/squeezelite
      regexp: 'SL_SOUNDCARD='
      line: SL_SOUNDCARD="hw:CARD=sndrpihifiberry,DEV=0"

  - name: Restart Squeezelite
    ansible.builtin.service:
      name: squeezelite
      state: restarted